name = "raquest"
version = "0.0.1"
description = "an easy HTTP client for Gleam"
licenses = ["MIT"]

repository = { type = "github", user = "raquentin", repo = "raquest" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
