name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y gcc g++ clang

      # Configure and build the project
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=23

      # Build the project
      - name: Build the project
        run: |
          cd build
          make

      # Run Google Tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
