name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Download Dependencies
        run: |
          sudo apt-get install ninja-build

      - name: Configure Build Directory
        run: |
          mkdir -p build
          cmake -G Ninja -S . -B build

      - name: Build
        run: |
          ninja -C build

      - name: Run Unit Tests
        run: |
          ninja runtests -C build
          ninja memcheck -C build

      - name: Run Valgrind
        run: |
          ninja valgrind -C build
