name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      # Install GCC and Clang linters (optional)
      - name: Install compilers and tools
        run: sudo apt-get install -y gcc clang clang-tidy cppcheck

      # Install dependencies using FetchContent (build all)
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..
      
      # Build the project
      - name: Build the project
        run: |
          cd build
          make

      # Run Google Tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # Run linter (optional, using clang-tidy or cppcheck)
      - name: Run linter (cppcheck)
        run: |
          cppcheck --enable=all --inconclusive --error-exitcode=1 src

      - name: Run clang-tidy
        run: |
          clang-tidy src/*.cpp -- -std=c++23
